### ISSUE TITLE
影子浮空，只能投影一个格子

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraftSDK#1]
![image 1](http://ww2.sinaimg.cn/mw1024/8ddab624gw1f14m7r8x6kj20700ckt9h.jpg)

![image 2](http://ww3.sinaimg.cn/mw1024/8ddab624gw1f14m7qkvh5j209404qt8w.jpg)

![image 3](http://ww2.sinaimg.cn/large/8ddab624gw1f14m7rt13kj214g0q24hn.jpg)

恩？望解决。

**Comment by LiXizhi** [comment]
simple stencil shadow by design. switch to shadowmap for real shadows.
