### ISSUE TITLE
/setcolor 命令无法正确识别颜色值

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraftSDK#2]
/setcolor #123456 
成了 103050
![/setcolor #123456 成了 103050](http://ww1.sinaimg.cn/mw1024/8ddab624gw1f1uerdryy7j20e002pdgl.jpg)
试过就知道

**Comment by LiXizhi** [comment]
Color is converted from 32bits to 16bits by design. 
color & #f0f0f0
