### ISSUE TITLE
光照系统

### ISSUE THREAD

**Issue by ExerciseBook** [LiXizhi/ParaCraftSDK#3]
![有问题的](http://ww3.sinaimg.cn/mw690/8ddab624gw1f3murow1boj20zk0pydin.jpg)

![有问题的1](http://ww1.sinaimg.cn/mw690/8ddab624gw1f3murp96o9j20we0i4mys.jpg)

在其他环境相同的状态下，将空间的正上方进行封闭之后，会发现该地区下方中心部分一大块区域都会变暗甚至全黑。以此导致该区域所笼罩体积下的一切物体都将变得乌黑以至于难以用肉眼观察。
此时即使铺设人工灯光（如萤石块）：一方面也不过只能照亮部分区域。况且由于方块形制不同（如全砖方块及半砖方块的透光能力不同），导致建筑材料看起来如同有斑点，不够整齐划一。另一方面在做一些对于传统意义要求较强的建筑时，如中式，需要考虑各个斗拱、榫卯、梁架之间的衔接关系，而在此时铺设灯光，会影响整体构造的效果，缺失逼真性。
因此，我建议尽量地加强光照系统的能力。尤其是在阳光无法照射的位置，应加强光线程度，在一方面不至于失真，另一方面也有助于玩家更好地建造大型建筑以不再更多地倚靠人工灯光的辅助。
希望能够得到响应，感谢。
——寂风

**Comment by LiXizhi** [comment]
无法复现黑色区域

**Comment by LiXizhi** [comment]
Fixed
